export const INTERNSHIP_LIST_REQUEST = 'INTERNSHIP_LIST_REQUEST';
export const INTERNSHIP_LIST_SUCCESS = 'INTERNSHIP_LIST_SUCCESS';
export const INTERNSHIP_LIST_FAIL = 'INTERNSHIP_LIST_FAIL';

export const INTERNSHIP_DETAILS_REQUEST = 'INTERNSHIP_DETAILS_REQUEST';
export const INTERNSHIP_DETAILS_SUCCESS = 'INTERNSHIP_DETAILS_SUCCESS';
export const INTERNSHIP_DETAILS_FAIL = 'INTERNSHIP_DETAILS_FAIL';

export const INTERNSHIP_CREATE_REQUEST = 'INTERNSHIP_CREATE_REQUEST';
export const INTERNSHIP_CREATE_SUCCESS = 'INTERNSHIP_CREATE_SUCCESS';
export const INTERNSHIP_CREATE_FAIL = 'INTERNSHIP_CREATE_FAIL';
export const INTERNSHIP_CREATE_RESET = 'INTERNSHIP_CREATE_RESET';

export const INTERNSHIP_UPDATE_REQUEST = 'INTERNSHIP_UPDATE_REQUEST';
export const INTERNSHIP_UPDATE_SUCCESS = 'INTERNSHIP_UPDATE_SUCCESS';
export const INTERNSHIP_UPDATE_FAIL = 'INTERNSHIP_UPDATE_FAIL';
export const INTERNSHIP_UPDATE_RESET = 'INTERNSHIP_UPDATE_RESET';

export const INTERNSHIP_DELETE_REQUEST = 'INTERNSHIP_DELETE_REQUEST';
export const INTERNSHIP_DELETE_SUCCESS = 'INTERNSHIP_DELETE_SUCCESS';
export const INTERNSHIP_DELETE_FAIL = 'INTERNSHIP_DELETE_FAIL';
export const INTERNSHIP_DELETE_RESET = 'INTERNSHIP_DELETE_FAIL';